name: test pipeline
on:
#  pull_request:
#    branches: [main]
 push:
   branches: [develop]


jobs:
 test-infra:
   runs-on: ubuntu-latest

   default: 
     run: 
       working-directory: staticwebsite

   permissions:
     id-token: write
     contents: read # This is required for actions/checkout@v2

   env:
     AWS_ROLE_ARN: arn:aws:iam::443420183404:role/github
     AWS_DEFAULT_REGION: us-east-1
     PLAN_NAME: main

   steps:
   - name: configureawscredentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       role-to-assume: ${{env.AWS_ROLE_ARN}}
       role-session-name: testrolesession
       aws-region: ${{env.AWS_DEFAULT_REGION}}

   - name: checkout
     uses: actions/checkout@v2

   - name: initialize terraform
     run: |
      #  version=0.14.9
       echo "installing tfenv ..."
       git clone https://github.com/tfutils/tfenv.git ~/.tfenv
       ~/.tfenv/bin/tfenv install $version
       ~/.tfenv/bin/tfenv use $version
       terraform init -upgrade
       terraform validate
       
   - name: plan staticwebsite
     run: |
       terraform plan -out ${{ env.PLAN_NAME }}      

